# Generated by Django 3.2.9 on 2022-02-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr2calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticslogtest',
            name='a_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='b_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='dark_index',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='delta_a_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='delta_b_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='delta_e_ab_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='delta_l_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='delta_uv',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='g2g',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='l_star',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='response_time',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='time_fall',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='time_rise',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='u_prime',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='v_prime',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='white_index',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='wx',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='wy',
            field=models.DecimalField(decimal_places=9, max_digits=20),
        ),
    ]
