# Generated by Django 3.2.9 on 2022-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr2calculator', '0002_auto_20220214_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticslogtest',
            name='transmittance',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
