# Generated by Django 3.2.9 on 2022-02-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr2calculator', '0003_alter_opticslogtest_transmittance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opticslogtest',
            name='v100',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='v90',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='v95',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='v99',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='opticslogtest',
            name='vop',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
