# Generated by Django 3.2.9 on 2022-02-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidCrystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a LC name', max_length=20, unique=True)),
                ('n_e', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('n_o', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('scatter_index', models.DecimalField(blank=True, decimal_places=9, max_digits=10, null=True)),
                ('phase', models.CharField(blank=True, choices=[('TR 1', 'TR 1'), ('TR 2', 'TR 2'), ('TR 3', 'TR 3'), ('TR 3.5', 'TR 3.5')], default='TR 2', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polyimide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a PI name', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Seal name', max_length=20, unique=True)),
            ],
        ),
    ]
