# Generated by Django 3.2.9 on 2022-02-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_liquidcrystal_vender'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidcrystal',
            name='designed_cell_gap',
            field=models.DecimalField(blank=True, decimal_places=1, default=3.0, max_digits=4),
        ),
    ]
