# Generated by Django 3.2.5 on 2021-11-25 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input file name', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidCrystal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a LC name', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polyimide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a PI name', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Seal name', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FOO', max_length=20, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vender name', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UV_aging', models.CharField(choices=[('Before UV', 'Before UV'), ('After UV', 'After UV')], default='Before UV', max_length=10)),
                ('measure_voltage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('measure_freq', models.DecimalField(decimal_places=2, default=0.6, max_digits=5)),
                ('measure_temperature', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
        migrations.CreateModel(
            name='LowTemperatureStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_condition', models.CharField(choices=[('Bulk', 'Bulk'), ('Test Cell', 'Test Cell')], max_length=10)),
                ('SLV_condition', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('measure_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('JarTestSeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ra_exploer.seal')),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
        migrations.CreateModel(
            name='LowTemperatureOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_condition', models.CharField(default='Test Cell', max_length=10)),
                ('SLV_condition', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('measure_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('value', models.IntegerField(choices=[(-1, 'N.A.'), (0, 'NG'), (1, 'Pass')], null=True)),
                ('JarTestSeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ra_exploer.seal')),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
        migrations.AddField(
            model_name='liquidcrystal',
            name='vender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender'),
        ),
        migrations.CreateModel(
            name='DeltaAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_voltage', models.DecimalField(decimal_places=2, default=14.0, max_digits=5)),
                ('measure_freq', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('measure_time', models.DecimalField(decimal_places=2, default=72.0, max_digits=5)),
                ('measure_temperature', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
        migrations.CreateModel(
            name='Adhesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhesion_interface', models.CharField(help_text='enter condition', max_length=40)),
                ('method', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peeling', models.CharField(blank=True, help_text='Enter peeling interface.', max_length=40, null=True)),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
    ]
