# Generated by Django 3.2.9 on 2022-02-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
