# Generated by Django 3.2.5 on 2021-11-25 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhr',
            name='valid_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.validator'),
        ),
    ]
