# Generated by Django 3.2.9 on 2021-11-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateitem',
            name='LC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal'),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='PI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide'),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='seal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal'),
        ),
        migrations.AlterField(
            model_name='templateitem',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vendor'),
        ),
    ]
