# Generated by Django 4.0.2 on 2022-02-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0002_validator_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sealwvtr',
            name='measure_condition_1',
        ),
        migrations.RemoveField(
            model_name='sealwvtr',
            name='measure_condition_2',
        ),
        migrations.AddField(
            model_name='sealwvtr',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sealwvtr',
            name='temperature',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sealwvtr',
            name='thickness',
            field=models.FloatField(default=0),
        ),
    ]
