# Generated by Django 3.2.9 on 2021-11-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0002_vhr_valid_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vhr',
            name='valid_value',
        ),
    ]
