# Generated by Django 3.2.9 on 2021-11-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0002_auto_20211114_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='conditon name', max_length=20)),
                ('desc', models.TextField(help_text='Enter the brief description of the condition', max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='templateitem',
            name='cond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.templatecond'),
        ),
    ]
