# Generated by Django 4.0.2 on 2022-02-28 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_liquidcrystal_designed_cell_gap'),
        ('ra_exploer', '0003_remove_sealwvtr_measure_condition_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UShapeAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.FloatField()),
                ('temperature', models.FloatField()),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='materials.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='materials.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='materials.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
    ]
