# Generated by Django 3.2.9 on 2021-11-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0003_remove_vhr_valid_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='venders',
            field=models.ManyToManyField(null=True, to='ra_exploer.Vender'),
        ),
    ]
