# Generated by Django 3.2.9 on 2021-11-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0004_vhr'),
    ]

    operations = [
        migrations.AddField(
            model_name='vhr',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
