# Generated by Django 3.2.9 on 2021-11-14 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0005_vhr_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhr',
            name='condition',
            field=models.CharField(choices=[('Before UV', 'Before UV'), ('After UV', 'After UV')], max_length=10),
        ),
    ]
