# Generated by Django 3.2.9 on 2021-11-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0006_alter_vhr_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_voltage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('measure_freq', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('file_source', models.CharField(help_text='file name', max_length=200)),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vendor')),
            ],
        ),
    ]
