# Generated by Django 3.2.5 on 2021-12-06 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0006_sealwvtr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sealwvtr',
            old_name='meashure_condition_1',
            new_name='measure_condition_1',
        ),
        migrations.RenameField(
            model_name='sealwvtr',
            old_name='meashure_condition_2',
            new_name='measure_condition_2',
        ),
    ]
