# Generated by Django 3.2.5 on 2021-11-16 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0008_adhesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhesion',
            name='judgement',
            field=models.CharField(choices=[('NG', 'NG'), ('OK', 'OK')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='LowTemperatrueStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_condtion', models.CharField(choices=[('Bulk', 'Bulk'), ('Test Cell', 'Test Cell')], max_length=10)),
                ('SLV_condtion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('measure_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('file_source', models.CharField(help_text='file name', max_length=200)),
                ('JarTestSeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ra_exploer.seal')),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
            ],
        ),
        migrations.CreateModel(
            name='LowTemperatrueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_condtion', models.CharField(choices=[('Bulk', 'Bulk'), ('Test Cell', 'Test Cell')], max_length=10)),
                ('SLV_condtion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('measure_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('value', models.CharField(blank=True, choices=[('OK', 'OK'), ('NG', 'NG')], max_length=10, null=True)),
                ('file_source', models.CharField(help_text='file name', max_length=200)),
                ('JarTestSeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ra_exploer.seal')),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
            ],
        ),
    ]
