# Generated by Django 3.2.5 on 2021-11-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0010_auto_20211116_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhr',
            name='measure_freq',
            field=models.DecimalField(decimal_places=2, default=0.6, max_digits=5),
        ),
        migrations.AlterField(
            model_name='vhr',
            name='measure_voltage',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
