# Generated by Django 3.2.5 on 2021-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0011_auto_20211116_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vhr',
            name='condition',
            field=models.CharField(choices=[('Before UV', 'Before UV'), ('After UV', 'After UV')], default='Before UV', max_length=10),
        ),
    ]
