# Generated by Django 3.2.5 on 2021-11-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0012_alter_vhr_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltaangle',
            name='measure_time',
            field=models.DecimalField(decimal_places=2, default=72.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='deltaangle',
            name='measure_freq',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='deltaangle',
            name='measure_voltage',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=5),
        ),
    ]
