# Generated by Django 3.2.5 on 2021-11-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0014_acis'),
    ]

    operations = [
        migrations.AddField(
            model_name='acis',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
