# Generated by Django 3.2.5 on 2021-11-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0015_acis_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acis',
            name='device',
            field=models.CharField(blank=True, default='2211 Test Cell', max_length=20, null=True),
        ),
    ]
