# Generated by Django 3.2.5 on 2021-11-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0017_auto_20211116_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowtemperatrueoperation',
            name='storage_condtion',
            field=models.CharField(default='Test Cell', max_length=10),
        ),
    ]
