# Generated by Django 3.2.5 on 2021-11-17 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0019_alter_lowtemperatrueoperation_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Input file name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vender name', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='deltaangle',
            name='LC',
        ),
        migrations.RemoveField(
            model_name='deltaangle',
            name='PI',
        ),
        migrations.RemoveField(
            model_name='deltaangle',
            name='seal',
        ),
        migrations.RemoveField(
            model_name='deltaangle',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='lowtemperatrueoperation',
            name='JarTestSeal',
        ),
        migrations.RemoveField(
            model_name='lowtemperatrueoperation',
            name='LC',
        ),
        migrations.RemoveField(
            model_name='lowtemperatrueoperation',
            name='PI',
        ),
        migrations.RemoveField(
            model_name='lowtemperatrueoperation',
            name='seal',
        ),
        migrations.RemoveField(
            model_name='lowtemperatrueoperation',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='lowtemperatruestorage',
            name='JarTestSeal',
        ),
        migrations.RemoveField(
            model_name='lowtemperatruestorage',
            name='LC',
        ),
        migrations.RemoveField(
            model_name='lowtemperatruestorage',
            name='PI',
        ),
        migrations.RemoveField(
            model_name='lowtemperatruestorage',
            name='seal',
        ),
        migrations.RemoveField(
            model_name='lowtemperatruestorage',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='LC',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='PI',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='cond',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='seal',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vhr',
            name='LC',
        ),
        migrations.RemoveField(
            model_name='vhr',
            name='PI',
        ),
        migrations.RemoveField(
            model_name='vhr',
            name='seal',
        ),
        migrations.RemoveField(
            model_name='vhr',
            name='vendor',
        ),
        migrations.RenameField(
            model_name='adhesion',
            old_name='condition',
            new_name='adhesion_interface',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='judgement',
        ),
        migrations.RemoveField(
            model_name='adhesion',
            name='vendor',
        ),
        migrations.AddField(
            model_name='adhesion',
            name='method',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='ACIS',
        ),
        migrations.DeleteModel(
            name='DeltaAngle',
        ),
        migrations.DeleteModel(
            name='LowTemperatrueOperation',
        ),
        migrations.DeleteModel(
            name='LowTemperatrueStorage',
        ),
        migrations.DeleteModel(
            name='TemplateCond',
        ),
        migrations.DeleteModel(
            name='TemplateItem',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VHR',
        ),
        migrations.AddField(
            model_name='adhesion',
            name='vender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='file_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file'),
        ),
    ]
