# Generated by Django 3.2.9 on 2021-11-17 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0020_auto_20211117_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(help_text='Input file name', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='liquidcrystal',
            name='name',
            field=models.CharField(help_text='Enter a LC name', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='polyimide',
            name='name',
            field=models.CharField(help_text='Enter a PI name', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='seal',
            name='name',
            field=models.CharField(help_text='Enter a Seal name', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vender',
            name='name',
            field=models.CharField(help_text='Vender name', max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='LowTemperatrueOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_condtion', models.CharField(default='Test Cell', max_length=10)),
                ('SLV_condtion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('measure_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('value', models.CharField(choices=[('OK', 'OK'), ('NG', 'NG'), ('N.A.', 'N.A.')], max_length=10, null=True)),
                ('file_source', models.CharField(help_text='file name', max_length=200)),
                ('JarTestSeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ra_exploer.seal')),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
    ]
