# Generated by Django 3.2.9 on 2021-11-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0021_auto_20211118_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowtemperatrueoperation',
            old_name='SLV_condtion',
            new_name='SLV_condition',
        ),
    ]
