# Generated by Django 3.2.9 on 2021-11-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0022_rename_slv_condtion_lowtemperatrueoperation_slv_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowtemperatrueoperation',
            old_name='storage_condtion',
            new_name='storage_condition',
        ),
    ]
