# Generated by Django 3.2.9 on 2021-11-17 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0023_rename_storage_condtion_lowtemperatrueoperation_storage_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowtemperatrueoperation',
            name='file_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file'),
        ),
        migrations.AlterField(
            model_name='lowtemperatrueoperation',
            name='value',
            field=models.CharField(choices=[('Pass', 'Pass'), ('NG', 'NG'), ('N.A.', 'N.A.')], max_length=10, null=True),
        ),
    ]
