# Generated by Django 3.2.9 on 2021-11-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0024_auto_20211118_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowTemperatrueStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_condition', models.CharField(choices=[('Bulk', 'Bulk'), ('Test Cell', 'Test Cell')], max_length=10)),
                ('SLV_condition', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('measure_temperature', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('JarTestSeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ra_exploer.seal')),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
    ]
