# Generated by Django 3.2.9 on 2021-11-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0025_lowtemperatruestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaAngle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_voltage', models.DecimalField(decimal_places=2, default=14.0, max_digits=5)),
                ('measure_freq', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('measure_time', models.DecimalField(decimal_places=2, default=72.0, max_digits=5)),
                ('measure_temperature', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
    ]
