# Generated by Django 3.2.9 on 2021-11-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0026_deltaangle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltaangle',
            name='measure_temperature',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, null=True),
        ),
    ]
