# Generated by Django 3.2.9 on 2021-11-17 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0027_alter_deltaangle_measure_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='VHR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UV_aging', models.CharField(choices=[('Before UV', 'Before UV'), ('After UV', 'After UV')], default='Before UV', max_length=10)),
                ('measure_voltage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('measure_freq', models.DecimalField(decimal_places=2, default=0.6, max_digits=5)),
                ('measure_temperature', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('LC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.liquidcrystal')),
                ('PI', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.polyimide')),
                ('file_source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.file')),
                ('seal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.seal')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='ra_exploer.vender')),
            ],
        ),
    ]
