# Generated by Django 3.2.5 on 2021-11-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0029_auto_20211119_1525'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LowTemperatrueOperation',
            new_name='LowTemperatureOperation',
        ),
    ]
