# Generated by Django 3.2.5 on 2021-11-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0030_rename_lowtemperatrueoperation_lowtemperatureoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowtemperatureoperation',
            name='value',
            field=models.IntegerField(choices=[(1, 'NG'), (2, 'PASS'), (3, 'N.A.')], null=True),
        ),
    ]
