# Generated by Django 3.2.5 on 2021-11-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra_exploer', '0032_alter_lowtemperatureoperation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowtemperatureoperation',
            name='value',
            field=models.IntegerField(choices=[(-1, 'N.A.'), (0, 'NG'), (1, 'Pass')], null=True),
        ),
    ]
